### ISSUE TITLE
addons-linter fails on CI

### ISSUE THREAD

**Issue by 1ec5** [1ec5/avim#199]
Builds on Travis are failing:

```
0.29s$ addons-linter *.xpi

/home/travis/.nvm/versions/node/v8.1.4/lib/node_modules/addons-linter/node_modules/find-up/index.js:29

		const foundPath = await runMatcher({...options, cwd: directory});

		                                    ^^^

SyntaxError: Unexpected token ...

    at createScript (vm.js:74:10)

    at Object.runInThisContext (vm.js:116:10)

    at Module._compile (module.js:533:28)

    at Object.Module._extensions..js (module.js:580:10)

    at Module.load (module.js:503:32)

    at tryModuleLoad (module.js:466:12)

    at Function.Module._load (module.js:458:3)

    at Module.require (module.js:513:17)

    at require (internal/module.js:11:18)

    at pkgUp (/home/travis/.nvm/versions/node/v8.1.4/lib/node_modules/addons-linter/node_modules/yargs/yargs.js:537:20)

The command "addons-linter *.xpi" exited with 1.
```

**Comment by 1ec5** [comment]
It’s probably because addons-linter [requires a newer version of Node.js](https://github.com/mozilla/addons-linter/blob/d7c82127b67b2170e7c47f0fdbbb0a9f2890457c/.nvmrc#L1) than the build bot is running.
